dist: trusty
sudo: false

language: cpp

cache:
  ccache: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:lkoppel/robotics'
    packages:
      - g++-5
      - libboost-dev
      - libyaml-cpp-dev
      - libeigen3-dev
      - libpcl-dev
      - libopencv-dev
      - libceres-dev
      - libkindr-dev
      - clang-format-3.8

install:
- |-
  mkdir -p "$HOME/deps"
  # GeographicLib dependency
  pushd "$HOME/deps"
  GEOGRAPHICLIB_ROOT="$PWD/GeographicLib-1.49"
  wget -nc 'https://sourceforge.net/projects/geographiclib/files/distrib/GeographicLib-1.49.tar.gz'
  tar xzf GeographicLib-1.49.tar.gz
  mkdir -p "${GEOGRAPHICLIB_ROOT}/build"
  pushd ${GEOGRAPHICLIB_ROOT}/build
  cmake ${GEOGRAPHICLIB_ROOT}
  make
  sudo make install
  popd
  popd
- |-

before_script:
  - export CXX=g++-5 CC=gcc-5  # override travis defaults

script:
  - bash scripts/ci/ci_check.bash
  - bash scripts/ci/ci_run.bash

notifications:
  email: false
