dist: trusty
sudo: false

language: cpp

cache:
  ccache: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:lkoppel/robotics'
      - sourceline: 'deb http://us.archive.ubuntu.com/ubuntu/ trusty universe'
    packages:
      - g++-5
      - libboost-dev
      - libyaml-cpp-dev
      - libeigen3-dev
      - libpcl-dev
      - libopencv-dev
      - libceres-dev
      - libkindr-dev
      - clang-format-3.8

install:
- |-
  # GeographicLib dependency
  mkdir -p "$HOME/deps"
  pushd "$HOME/deps"
  GEOGRAPHICLIB_ROOT="$PWD/GeographicLib-1.49"
  if [ -d ${GEOGRAPHICLIB_ROOT} ]; then
    echo "using GeographicLib from Travis cache"
  else
    wget -nc 'http://archive.ubuntu.com/ubuntu/pool/universe/g/geographiclib/libgeographic-dev_1.49-2_amd64.deb'
    sudo dpkg -i libgeographic-dev_1.49-2_amd64.deb
  fi
  popd
- |-

before_script:
  - export CXX=g++-5 CC=gcc-5  # override travis defaults

script:
  - bash scripts/ci/ci_check.bash
  - bash scripts/ci/ci_run.bash

notifications:
  email: false
